const BatchEngine = {
    id: 'Batch',
    name: 'Batch Script',
    icon: 'terminal',
    fileExtension: '.bat',
    
    // Use the global variables from data.js
    get commands() { return typeof commandLibrary !== 'undefined' ? commandLibrary : []; },
    get presets() { return typeof presetLibrary !== 'undefined' ? presetLibrary : []; },

    generateCode: function(returnLines = false) {
        const dropZone = document.getElementById('dropZone');
        const blocks = dropZone.querySelectorAll('.script-block');
        let outputLines = [];
        const addLine = (text, blockIdx = null) => outputLines.push({ text, blockIndex: blockIdx });

        addLine("@ECHO OFF");
        addLine("REM Generated by WinScript Builder");
        addLine("");

        let indentLevel = 0;
        blocks.forEach((block, index) => {
            const id = block.getAttribute('data-cmd-id');
            const values = Array.from(block.querySelectorAll('.cmd-input')).map(i => i.value);
            const cmd = this.commands.find(c => c.id === id);
            
            if(cmd && (cmd.isContainerEnd || cmd.isContainerMid)) indentLevel = Math.max(0, indentLevel - 1);
            
            let line = "";
            const getVal = (v) => { const match = v.match(/\((.*?)\)/); return match ? match[1] : v; };
            const indent = "    ".repeat(indentLevel);
            
            // Helper for escaping batch strings in Python generation
            const escapeBatchStr = (str) => str.replace(/%/g, '%%').replace(/\^/g, '^^').replace(/&/g, '^&').replace(/</g, '^<').replace(/>/g, '^>').replace(/\|/g, '^|');

            if(id === 'py_run' && block.dataset.scriptContent) {
                const scriptName = values[0];
                const lines = block.dataset.scriptContent.split('\n');
                addLine(`${indent}REM --- Generating ${scriptName} ---`, index + 1);
                addLine(`${indent}(`, index + 1);
                lines.forEach(l => addLine(`${indent}echo ${escapeBatchStr(l)}`, index + 1));
                addLine(`${indent}) > ${scriptName}`, index + 1);
                addLine("", index + 1);
            }

            // --- Command Mapping Logic (Moved from script.js) ---
            if(id === 'if_start') { 
                const [t, tgt, val] = values; 
                if(t.includes('EQU')) line = `IF "${tgt}"=="${val}" (`; 
                else if(t.includes('NEQ')) line = `IF "${tgt}" NEQ "${val}" (`;
                else if(t.includes('DEFINED')) line = `IF ${t} ${tgt} (`;
                else line = `IF ${t} "${tgt}" (`; 
            }
            else if(id === 'else_start') line = `) ELSE (`;
            else if(id === 'block_end') line = `)`;
            else if(id === 'shutdown') line = `SHUTDOWN ${getVal(values[0])} /t ${values[1]}`;
            else if(id === 'for_loop') line = `FOR ${values[0]} IN ${values[1]} DO (`;
            else if(id === 'set') line = `SET "${values[0]}=${values[1]}"`;
            else if(id === 'set_p') line = `SET /P "${values[0]}=${values[1]}"`;
            else if(id === 'choice') line = `CHOICE /C ${values[1] || 'YN'} /M "${values[0]}"`;
            else if(id === 'timeout') line = `TIMEOUT /T ${values[0]} /NOBREAK`;
            else if(id === 'mklink') { const type = getVal(values[0]); line = `MKLINK ${type === 'File' ? '' : type} "${values[1]}" "${values[2]}"`; }
            else if(id === 'custom_cmd') line = `REM [Custom] ${values[0]}\r\n${"    ".repeat(indentLevel)}${values[0]}`;
            else if(id === 'color') line = `COLOR ${values[0].substring(0,2)}`;
            else if(id === 'del') line = values[1].includes('Yes') ? `DEL /F /Q "${values[0]}"` : `DEL "${values[0]}"`;
            else if(id === 'rd') line = values[1].includes('Yes') ? `RMDIR /S /Q "${values[0]}"` : `RMDIR "${values[0]}"`;
            else if(id === 'md') line = `MKDIR "${values[0]}"`;
            else if(id === 'copy') line = `COPY "${values[0]}" "${values[1]}"`;
            else if(id === 'move') line = `MOVE "${values[0]}" "${values[1]}"`;
            else if(id === 'ren') line = `REN "${values[0]}" "${values[1]}"`;
            else if(id === 'type') line = `TYPE "${values[0]}"`;
            else if(id === 'attrib') line = `ATTRIB ${values[0]} "${values[1]}"`;
            else if(id === 'xcopy') line = `XCOPY "${values[0]}" "${values[1]}" ${values[2]}`;
            else if(id === 'robocopy') line = `ROBOCOPY "${values[0]}" "${values[1]}" ${values[2]}`;
            else if(id === 'ipconfig') line = `IPCONFIG ${getVal(values[0])}`;
            else if(id === 'echo_to_file') line = `ECHO ${values[0]} ${values[2].includes('>>') ? '>>' : '>'} "${values[1]}"`;
            
            // System, Git, Python, Java, Archive mappings...
            else if(id.startsWith('git_')) {
                const action = id.replace('git_', '');
                if(action === 'commit') line = `git commit -m "${values[0]}"`;
                else if(action === 'add') line = `git add ${values[0]}`;
                else if(action === 'clone') line = `git clone ${values[0]}`;
                else if(action === 'checkout') line = `git checkout ${values[0]}`;
                else line = `git ${action}`;
            }
            else if(id === 'py_venv') line = `python -m venv ${values[0]}`;
            else if(id === 'pip_install') line = `pip install ${values[0]}`;
            else if(id === 'pip_freeze') line = `pip freeze > ${values[0]}`;
            else if(id === 'pip_upgrade') line = `python -m pip install --upgrade pip`;
            else if(id === 'java_run') line = `java ${values[0]} ${values[1]}`;
            else if(id === 'javac') line = `javac ${values[1]} ${values[0]}`;
            else if(id === 'jar_create') line = `jar ${values[2] || 'cf'} "${values[0]}" ${values[1]}`;
            else if(id === 'jar_extract') line = `jar ${values[1] || 'xf'} "${values[0]}"`;
            else if(id === 'javadoc') line = `javadoc ${values[1]} ${values[0]}`;
            else if(id === 'java_version') line = `java -version`;
            else if(id === 'jps') line = `jps ${values[0]}`;
            else if(id === 'jshell') line = `jshell`;
            else if(id === 'keytool_gen') line = `keytool -genkeypair -alias "${values[1]}" -keyalg RSA -keysize 2048 -keystore "${values[0]}" -validity 365`;
            else if(id === 'keytool_list') line = `keytool -list -v -keystore "${values[0]}"`;
            else if(id === '7zip_create') line = `7z a "${values[0]}" ${values[1]} ${values[2]}`;
            else if(id === '7zip_extract') line = `7z x "${values[0]}" ${values[1]}`;
            else if(id.startsWith('net_') && id !== 'netstat') line = `NET ${id.replace('net_', '').toUpperCase()} ${values.join(' ')}`;
            else line = `${cmd.name.split(' ')[0]} ${values.join(' ')}`;

            if (line) {
                const parts = line.split(/\r?\n/);
                parts.forEach((part, pIdx) => {
                    addLine((pIdx === 0 ? indent : "") + part, index + 1);
                });
            }

            if(cmd && (cmd.isContainerStart || cmd.isContainerMid)) indentLevel++;
        });
        
        if (returnLines) return outputLines;
        return outputLines.map(l => l.text).join('\r\n');
    },

    highlightSyntax: function(text) {
        let html = text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
        if (/^\s*(REM|::)/i.test(html)) return html.replace(/^(\s*)(.*)$/, '$1<span class="token-comment">$2</span>');
        
        const strings = [];
        html = html.replace(/(".*?")/g, (match) => { strings.push(match); return `__STR${strings.length-1}__`; });

        const keywords = "IF|ELSE|FOR|IN|DO|ECHO|SET|GOTO|EXIT|PAUSE|CLS|TITLE|COLOR|CD|MD|RD|DEL|COPY|MOVE|REN|TYPE|ATTRIB|XCOPY|ROBOCOPY|IPCONFIG|PING|NET|SCHTASKS|SC|ICACLS|GIT|PYTHON|PIP|JAVA|JAVAC|JAR|JAVADOC|7Z|CHOICE|TIMEOUT|MKLINK|SHUTDOWN|TASKKILL|TASKLIST|SYSTEMINFO|REG|PATH|ASSOC|FTYPE|DATE|TIME|MODE|OPENFILES|DRIVERQUERY|GPRESULT|VER|CALL|SHIFT";
        const kwRegex = new RegExp(`\\b(${keywords})\\b`, 'gi');
        html = html.replace(kwRegex, '<span class="token-keyword">$1</span>');
        html = html.replace(/^(\s*)(:[a-zA-Z0-9_-]+)/g, '$1<span class="token-label">$2</span>');
        html = html.replace(/(%[\w\*\?]+%|![\w]+!|%%[a-z])/gi, '<span class="token-variable">$1</span>');
        html = html.replace(/\b(\d+)\b/g, '<span class="token-number">$1</span>');
        html = html.replace(/__STR(\d+)__/g, (match, i) => `<span class="token-string">${strings[i]}</span>`);
        return html;
    },

    parse: function(text) {
        const lines = text.split(/\r?\n/);
        const blocks = [];
        lines.forEach(line => {
            line = line.trim();
            if(!line) return;
            const parts = line.split(/\s+/);
            const cmdName = parts[0].toUpperCase();
            const args = line.substring(cmdName.length).trim();

            if(cmdName === 'ECHO') blocks.push({id:'echo', values:[args]});
            else if(cmdName === 'REM') blocks.push({id:'rem', values:[args]});
            else if(cmdName === 'TITLE') blocks.push({id:'title', values:[args]});
            else if(cmdName === 'CLS') blocks.push({id:'cls', values:[]});
            else if(cmdName === 'PAUSE') blocks.push({id:'pause', values:[]});
            else if(line.toUpperCase() === '@ECHO OFF') blocks.push({id:'echo_off', values:[]});
            else if(cmdName === 'CD') blocks.push({id:'cd', values:[args]});
            else if(cmdName === 'GOTO') blocks.push({id:'goto', values:[args]});
            else if(cmdName === 'EXIT') blocks.push({id:'exit', values:[]});
            else if(cmdName === 'SET') {
                const eqIndex = args.indexOf('=');
                if(eqIndex > -1) blocks.push({id:'set', values:[args.substring(0, eqIndex), args.substring(eqIndex+1)]});
                else blocks.push({id:'custom_cmd', values:[line]});
            }
            else blocks.push({id:'custom_cmd', values:[line]});
        });
        return blocks;
    }
};