// --- STATIC DATA & CONFIGURATION ---

const commonIcons = [
    'terminal', 'code', 'bug_report', 'network_check', 'folder_open', 'save', 'cloud_upload', 'settings',
    'rocket_launch', 'build', 'security', 'lock', 'visibility', 'search', 'edit', 'delete', 'download',
    'upload', 'sync', 'wifi', 'router', 'dns', 'public', 'language', 'schedule', 'update', 'power_settings_new',
    'restart_alt', 'memory', 'cpu'
];

const commandLibrary = [
    // BASIC / CORE
    { id: 'echo', name: 'ECHO', cat: 'Basic', icon: 'campaign', desc: 'Display a message', useCase: 'ECHO Hello World', fields: [{ label: 'Message', type: 'text', placeholder: 'Hello World', req: true }] },
    { id: 'echo_off', name: '@ECHO OFF', cat: 'Basic', icon: 'visibility_off', desc: 'Hide background commands', useCase: '@ECHO OFF (Start of script)', fields: [] },
    { id: 'echo_on', name: '@ECHO ON', cat: 'Basic', icon: 'visibility', desc: 'Show background commands', useCase: '@ECHO ON', fields: [] },
    { id: 'cls', name: 'CLS', cat: 'Basic', icon: 'clear_all', desc: 'Clear the console window', useCase: 'CLS', fields: [] },
    { id: 'pause', name: 'PAUSE', cat: 'Basic', icon: 'pause_circle', desc: 'Wait for user to press a key', useCase: 'PAUSE', fields: [] },
    { id: 'title', name: 'TITLE', cat: 'Basic', icon: 'title', desc: 'Set the window title', useCase: 'TITLE My Script', fields: [{ label: 'Window Title', type: 'text', placeholder: 'My App', req: true }] },
    { id: 'color', name: 'COLOR', cat: 'Basic', icon: 'palette', desc: 'Change text/background color', useCase: 'COLOR 0A (Green on Black)', fields: [{ label: 'Color Code', type: 'select', options: ['07 (Default)', '0A (Green)', '0B (Aqua)', '0C (Red)', '0E (Yellow)', 'F0 (Black on White)'], req: true }] },
    { id: 'rem', name: 'REM', cat: 'Basic', icon: 'comment', desc: 'Add a note (Ignored by script)', useCase: 'REM This is a comment', fields: [{ label: 'Comment', type: 'text', placeholder: 'This is a comment' }] },
    { id: 'set', name: 'SET', cat: 'Basic', icon: 'functions', desc: 'Create a variable', useCase: 'SET myVar=123', fields: [{ label: 'Variable', type: 'text', placeholder: 'myVar', req: true }, { label: 'Value', type: 'text', placeholder: 'value' }] },
    { id: 'set_p', name: 'SET /P', cat: 'Basic', icon: 'keyboard', desc: 'Ask user for input', useCase: 'SET /P name="Enter name: "', fields: [{ label: 'Variable', type: 'text', req: true }, { label: 'Prompt Text', type: 'text' }] },
    { id: 'start', name: 'START', cat: 'Basic', icon: 'open_in_new', desc: 'Open a program or website', useCase: 'START chrome.exe google.com', fields: [{ label: 'Target', type: 'text' }] },
    { id: 'call', name: 'CALL', cat: 'Basic', icon: 'call_merge', desc: 'Call another script', useCase: 'CALL sub.bat', fields: [{ label: 'Script', type: 'text', req: true }] },
    { id: 'prompt', name: 'PROMPT', cat: 'Basic', icon: 'edit_note', desc: 'Change command prompt', useCase: 'PROMPT $P$G', fields: [{ label: 'Prompt Text', type: 'text', placeholder: '$P$G' }] },
    { id: 'chcp', name: 'CHCP', cat: 'Basic', icon: 'translate', desc: 'Change code page', useCase: 'CHCP 65001 (UTF-8)', fields: [{ label: 'Code Page', type: 'text', placeholder: '437' }] },
    { id: 'graphtabl', name: 'GRAPHTABL', cat: 'Basic', icon: 'schema', desc: 'Display extended charset', useCase: 'GRAPHTABL', fields: [] },

    // FLOW
    { id: 'if_start', name: 'IF (Start)', cat: 'Flow', icon: 'alt_route', desc: 'Start conditional block', isContainerStart: true, useCase: 'IF EXIST file.txt (...)', fields: [{ label: 'Condition Type', type: 'select', options: ['EXIST', 'NOT EXIST', 'DEFINED', 'NOT DEFINED', 'EQU (==)', 'NEQ (!=)'], req: true }, { label: 'Target', type: 'text', req: true }, { label: 'Compare Value', type: 'text' }] },
    { id: 'else_start', name: 'ELSE (Start)', cat: 'Flow', icon: 'call_split', desc: 'Else block', isContainerMid: true, useCase: '... ) ELSE ( ...', fields: [] },
    { id: 'block_end', name: 'END BLOCK', cat: 'Flow', icon: 'close_fullscreen', desc: 'Closes IF or FOR block', isContainerEnd: true, useCase: ')', fields: [] },
    { id: 'for_loop', name: 'FOR Loop', cat: 'Flow', icon: 'repeat', desc: 'Iterate items', isContainerStart: true, useCase: 'FOR %%G IN (*.txt) DO (...)', fields: [{ label: 'Variable', type: 'text', placeholder: '%%G' }, { label: 'Items (Set)', type: 'text', placeholder: '(*.*)' }] },
    { id: 'goto', name: 'GOTO', cat: 'Flow', icon: 'redo', desc: 'Jump to label', useCase: 'GOTO :LabelName', fields: [{ label: 'Label Name', type: 'text', req: true }] },
    { id: 'label', name: ':LABEL', cat: 'Flow', icon: 'label', desc: 'Define jump target', useCase: ':LabelName', fields: [{ label: 'Label Name', type: 'text', req: true }] },
    { id: 'call_label', name: 'CALL :label', cat: 'Flow', icon: 'subdirectory_arrow_right', desc: 'Call a subroutine', useCase: 'CALL :mySubroutine', fields: [{ label: 'Subroutine Label', type: 'text', req: true }] },
    { id: 'goto_eof', name: 'GOTO :EOF', cat: 'Flow', icon: 'keyboard_return', desc: 'Return from subroutine', useCase: 'GOTO :EOF', fields: [] },
    { id: 'choice', name: 'CHOICE', cat: 'Flow', icon: 'rule', desc: 'User choice Y/N', useCase: 'CHOICE /C YN /M "Continue?"', fields: [{ label: 'Message', type: 'text' }, { label: 'Options', type: 'text', placeholder: 'YN' }] },
    { id: 'timeout', name: 'TIMEOUT', cat: 'Flow', icon: 'timer', desc: 'Wait seconds', useCase: 'TIMEOUT /T 10', fields: [{ label: 'Seconds', type: 'number', placeholder: '10', req: true }] },
    { id: 'exit', name: 'EXIT', cat: 'Flow', icon: 'logout', desc: 'Exit script', useCase: 'EXIT /B 0', fields: [] },
    { id: 'pushd', name: 'PUSHD', cat: 'Flow', icon: 'save', desc: 'Store current directory', useCase: 'PUSHD C:\\MyFolder', fields: [{ label: 'Path', type: 'text' }] },
    { id: 'popd', name: 'POPD', cat: 'Flow', icon: 'restore', desc: 'Restore saved directory', useCase: 'POPD', fields: [] },
    { id: 'setlocal', name: 'SETLOCAL', cat: 'Flow', icon: 'layers', desc: 'Start local environment', useCase: 'SETLOCAL', fields: [] },
    { id: 'endlocal', name: 'ENDLOCAL', cat: 'Flow', icon: 'layers_clear', desc: 'End local environment', useCase: 'ENDLOCAL', fields: [] },
    { id: 'cmd', name: 'CMD', cat: 'Flow', icon: 'terminal', desc: 'Start command interpreter', useCase: 'CMD /C "echo Hello"', fields: [{ label: 'Arguments', type: 'text', placeholder: '/C "command"' }] },

    // FILE SYSTEM
    { id: 'cd', name: 'CD', cat: 'FileSystem', icon: 'folder_open', desc: 'Change directory', useCase: 'CD C:\\Windows', fields: [{ label: 'Path', type: 'text' }] },
    { id: 'md', name: 'MKDIR', cat: 'FileSystem', icon: 'create_new_folder', desc: 'Create folder', useCase: 'MKDIR NewFolder', fields: [{ label: 'Folder Name', type: 'text', req: true }] },
    { id: 'rd', name: 'RMDIR', cat: 'FileSystem', icon: 'folder_delete', desc: 'Delete folder', useCase: 'RMDIR /S /Q OldFolder', fields: [{ label: 'Folder', type: 'text', req: true }, { label: 'Quiet Mode', type: 'select', options: ['No', 'Yes (/Q/S)'] }] },
    { id: 'del', name: 'DEL', cat: 'FileSystem', icon: 'delete', desc: 'Delete file', useCase: 'DEL /F /Q file.txt', fields: [{ label: 'File', type: 'text', req: true }, { label: 'Force', type: 'select', options: ['No', 'Yes (/F/Q)'] }] },
    { id: 'ren', name: 'REN', cat: 'FileSystem', icon: 'edit', desc: 'Rename file or folder', useCase: 'REN old.txt new.txt', fields: [{ label: 'Old Name', type: 'text', req: true }, { label: 'New Name', type: 'text', req: true }] },
    { id: 'copy', name: 'COPY', cat: 'FileSystem', icon: 'content_copy', desc: 'Copy file', useCase: 'COPY source.txt dest.txt', fields: [{ label: 'Source', type: 'text', req: true }, { label: 'Dest', type: 'text', req: true }] },
    { id: 'move', name: 'MOVE', cat: 'FileSystem', icon: 'drive_file_move', desc: 'Move file', useCase: 'MOVE file.txt C:\\Folder', fields: [{ label: 'Source', type: 'text', req: true }, { label: 'Dest', type: 'text', req: true }] },
    { id: 'robocopy', name: 'ROBOCOPY', cat: 'FileSystem', icon: 'copy_all', desc: 'Robust File Copy', useCase: 'ROBOCOPY C:\\Src C:\\Dst /MIR', fields: [{ label: 'Source', type: 'text', req: true }, { label: 'Dest', type: 'text', req: true }, { label: 'Flags', type: 'text', placeholder: '/MIR' }] },
    { id: 'xcopy', name: 'XCOPY', cat: 'FileSystem', icon: 'file_copy', desc: 'Copy files & trees', useCase: 'XCOPY C:\\Src D:\\Dest /E', fields: [{ label: 'Source', type: 'text', req: true }, { label: 'Destination', type: 'text', req: true }, { label: 'Flags', type: 'text', placeholder: '/E /H /C /I' }] },
    { id: 'replace', name: 'REPLACE', cat: 'FileSystem', icon: 'find_replace', desc: 'Replace files', useCase: 'REPLACE C:\\Src\\*.dll C:\\Dest /S', fields: [{ label: 'Source', type: 'text', req: true }, { label: 'Destination', type: 'text' }, { label: 'Flags', type: 'text', placeholder: '/S' }] },
    { id: 'attrib', name: 'ATTRIB', cat: 'FileSystem', icon: 'verified', desc: 'File attributes', fields: [{ label: 'Attributes', type: 'text', placeholder: '+h' }, { label: 'File', type: 'text', req: true }] },
    { id: 'tree', name: 'TREE', cat: 'FileSystem', icon: 'account_tree', desc: 'Display dir tree', useCase: 'TREE C:\\Projects', fields: [{ label: 'Path', type: 'text' }] },
    { id: 'dir', name: 'DIR', cat: 'FileSystem', icon: 'list', desc: 'List files and folders', useCase: 'DIR C:\\Users', fields: [{ label: 'Path', type: 'text', placeholder: '(current dir)' }] },
    { id: 'type', name: 'TYPE', cat: 'FileSystem', icon: 'description', desc: 'Display a text file', useCase: 'TYPE my_file.txt', fields: [{ label: 'File', type: 'text', req: true }] },
    { id: 'echo_to_file', name: 'ECHO > file', cat: 'FileSystem', icon: 'note_add', desc: 'Write text to a file', useCase: 'ECHO "My text" > file.txt', fields: [{ label: 'Text', type: 'text', req: true }, { label: 'File', type: 'text', req: true }, { label: 'Mode', type: 'select', options: ['Overwrite (>)', 'Append (>>)'] }] },
    { id: 'find', name: 'FIND', cat: 'FileSystem', icon: 'search', desc: 'Search for string', useCase: 'FIND "error" log.txt', fields: [{ label: 'String', type: 'text', req: true }, { label: 'File(s)', type: 'text', req: true }] },
    { id: 'findstr', name: 'FINDSTR', cat: 'FileSystem', icon: 'saved_search', desc: 'Advanced string search', useCase: 'FINDSTR /R /C:"^[0-9]" *.log', fields: [{ label: 'String/Regex', type: 'text', req: true }, { label: 'File(s)', type: 'text', req: true }, { label: 'Flags', type: 'text', placeholder: '/S /I' }] },
    { id: 'print', name: 'PRINT', cat: 'FileSystem', icon: 'print', desc: 'Print a text file', useCase: 'PRINT report.txt', fields: [{ label: 'File', type: 'text', req: true }] },
    { id: 'verify', name: 'VERIFY', cat: 'FileSystem', icon: 'verified_user', desc: 'Verify file writes', useCase: 'VERIFY ON', fields: [{ label: 'Setting', type: 'select', options: ['ON', 'OFF'], req: true }] },
    { id: 'comp', name: 'COMP', cat: 'FileSystem', icon: 'compare', desc: 'Compare two files', useCase: 'COMP file1.txt file2.txt', fields: [{ label: 'File 1', type: 'text', req: true }, { label: 'File 2', type: 'text', req: true }] },
    { id: 'fc', name: 'FC', cat: 'FileSystem', icon: 'rule', desc: 'Compare two files (ext)', useCase: 'FC /L file1.txt file2.txt', fields: [{ label: 'File 1', type: 'text', req: true }, { label: 'File 2', type: 'text', req: true }, { label: 'Flags', type: 'text', placeholder: '/L /N' }] },
    { id: 'sort', name: 'SORT', cat: 'FileSystem', icon: 'sort', desc: 'Sort lines in a file', useCase: 'SORT input.txt > output.txt', fields: [{ label: 'File or Input', type: 'text', req: true }, { label: 'Flags', type: 'text', placeholder: '/R' }] },
    { id: 'subst', name: 'SUBST', cat: 'FileSystem', icon: 'link', desc: 'Map path to drive', useCase: 'SUBST Z: C:\\Users\\user\\docs', fields: [{ label: 'Drive', type: 'text', placeholder: 'Z:', req: true }, { label: 'Path', type: 'text', req: true }] },
    { id: 'chkdsk', name: 'CHKDSK', cat: 'FileSystem', icon: 'healing', desc: 'Check disk for errors', useCase: 'CHKDSK C: /F', fields: [{ label: 'Volume', type: 'text', placeholder: 'C:', req: true }, { label: 'Flags', type: 'text', placeholder: '/F /R' }] },
    { id: 'chkntfs', name: 'CHKNTFS', cat: 'FileSystem', icon: 'manage_search', desc: 'Check NTFS volume', useCase: 'CHKNTFS C:', fields: [{ label: 'Volume', type: 'text', placeholder: 'C:', req: true }] },
    { id: 'format', name: 'FORMAT', cat: 'FileSystem', icon: 'storage', desc: 'Format a volume (DANGER!)', useCase: 'FORMAT D: /FS:NTFS /Q', fields: [{ label: 'Volume', type: 'text', req: true }, { label: 'Flags', type: 'text', placeholder: '/Q' }] },
    { id: 'compact', name: 'COMPACT', cat: 'FileSystem', icon: 'compress', desc: 'Compress files/folders', useCase: 'COMPACT /C /S:C:\\Temp', fields: [{ label: 'Flags', type: 'text', placeholder: '/C /S', req: true }, { label: 'Path', type: 'text', req: true }] },
    { id: 'vol', name: 'VOL', cat: 'FileSystem', icon: 'album', desc: 'Display volume label', useCase: 'VOL C:', fields: [{ label: 'Drive', type: 'text', placeholder: 'C:' }] },
    { id: 'recover', name: 'RECOVER', cat: 'FileSystem', icon: 'restore_page', desc: 'Recover damaged file', useCase: 'RECOVER D:\\file.dat', fields: [{ label: 'File', type: 'text', req: true }] },
    { id: 'label', name: 'LABEL', cat: 'FileSystem', icon: 'label_outline', desc: 'Create volume label', useCase: 'LABEL C: MyDisk', fields: [{ label: 'Drive', type: 'text', placeholder: 'C:', req: true }, { label: 'Label', type: 'text' }] },
    { id: 'mklink', name: 'MKLINK', cat: 'FileSystem', icon: 'add_link', desc: 'Create a symbolic link', useCase: 'MKLINK /D \\MyLink \\Users\\User\\Docs', fields: [{ label: 'Type', type: 'select', options: ['File', 'Directory (/D)', 'Junction (/J)'] }, { label: 'Link Name', type: 'text', req: true }, { label: 'Target', type: 'text', req: true }] },
    { id: 'convert', name: 'CONVERT', cat: 'FileSystem', icon: 'published_with_changes', desc: 'Convert FAT to NTFS', useCase: 'CONVERT D: /FS:NTFS', fields: [{ label: 'Volume', type: 'text', req: true }, { label: 'FS', type: 'text', placeholder: '/FS:NTFS', req: true }] },

    // SYSTEM
    { id: 'shutdown', name: 'SHUTDOWN', cat: 'System', icon: 'power_settings_new', desc: 'Power control', fields: [{ label: 'Action', type: 'select', options: ['Shutdown (/s)', 'Restart (/r)', 'Logoff (/l)', 'Abort (/a)'] }, { label: 'Time (sec)', type: 'number', placeholder: '0', req: true }] },
    { id: 'taskkill', name: 'TASKKILL', cat: 'System', icon: 'cancel', desc: 'Kill process', fields: [{ label: 'Process Name', type: 'text', placeholder: 'notepad.exe', req: true }, { label: 'Force', type: 'select', options: ['Yes (/F)', 'No'] }] },
    { id: 'tasklist', name: 'TASKLIST', cat: 'System', icon: 'list_alt', desc: 'List processes', fields: [] },
    { id: 'systeminfo', name: 'SYSTEMINFO', cat: 'System', icon: 'info', desc: 'System info', fields: [] },
    { id: 'reg', name: 'REG', cat: 'System', icon: 'settings_system_daydream', desc: 'Registry Tool', fields: [{ label: 'Command', type: 'text', req: true }] },
    { id: 'path', name: 'PATH', cat: 'System', icon: 'traffic', desc: 'Set executable search path', useCase: 'PATH C:\\Python;%PATH%', fields: [{ label: 'New Path', type: 'text' }] },
    { id: 'assoc', name: 'ASSOC', cat: 'System', icon: 'assignment', desc: 'Associate file extension', useCase: 'ASSOC .xyz=MyFileType', fields: [{ label: 'Extension', type: 'text', req: true }, { label: 'File Type', type: 'text' }] },
    { id: 'ftype', name: 'FTYPE', cat: 'System', icon: 'integration_instructions', desc: 'Define file open command', useCase: 'FTYPE MyFileType="C:\\program.exe" "%1"', fields: [{ label: 'File Type', type: 'text', req: true }, { label: 'Open Command', type: 'text' }] },
    { id: 'date', name: 'DATE', cat: 'System', icon: 'today', desc: 'Display or set date', useCase: 'DATE /T', fields: [{ label: 'New Date (or /T)', type: 'text', placeholder: '/T or mm-dd-yy' }] },
    { id: 'time', name: 'TIME', cat: 'System', icon: 'watch', desc: 'Display or set time', useCase: 'TIME /T', fields: [{ label: 'New Time (or /T)', type: 'text', placeholder: '/T or hh:mm' }] },
    { id: 'mode', name: 'MODE', cat: 'System', icon: 'settings_ethernet', desc: 'Configure system devices', useCase: 'MODE COM1:9600,N,8,1', fields: [{ label: 'Device', type: 'text', req: true }, { label: 'Parameters', type: 'text' }] },
    { id: 'openfiles', name: 'OPENFILES', cat: 'System', icon: 'folder_shared', desc: 'Manage open files', useCase: 'OPENFILES /query /V', fields: [{ label: 'Arguments', type: 'text', placeholder: '/query /V', req: true }] },
    { id: 'openfiles_disconnect', name: 'OPENFILES Disconnect', cat: 'System', icon: 'link_off', desc: 'Disconnect remotely opened files.', useCase: 'OPENFILES /disconnect /id 123', fields: [{ label: 'ID/Path/User', type: 'text', req: true, placeholder: '/id 123' }] },
    { id: 'openfiles_local', name: 'OPENFILES Local Tracking', cat: 'System', icon: 'track_changes', desc: 'Enable/disable local file handle tracking.', useCase: 'OPENFILES /local on', fields: [{ label: 'State', type: 'select', options: ['on', 'off'], req: true }] },
    { id: 'driverquery', name: 'DRIVERQUERY', cat: 'System', icon: 'memory', desc: 'List installed drivers', useCase: 'DRIVERQUERY /V', fields: [{ label: 'Flags', type: 'text', placeholder: '/V /SI' }] },
    { id: 'gpresult', name: 'GPRESULT', cat: 'System', icon: 'policy', desc: 'Display Group Policy', useCase: 'GPRESULT /R', fields: [{ label: 'Flags', type: 'text', placeholder: '/R' }] },
    { id: 'ver', name: 'VER', cat: 'System', icon: 'badge', desc: 'Display Windows version', useCase: 'VER', fields: [] },
    // --- Service Control ---
    { id: 'sc', name: 'SC (Advanced)', cat: 'System', icon: 'build', desc: 'Advanced Service Control manager', useCase: 'SC query state= all', fields: [{ label: 'Command', type: 'text', placeholder: 'query', req: true }, { label: 'Service Name', type: 'text' }, { label: 'Arguments', type: 'text' }] },
    { id: 'sc_query', name: 'SC QUERY', cat: 'System', icon: 'help', desc: 'Query a service status', useCase: 'SC QUERY MyService', fields: [{ label: 'Service Name', type: 'text' }] },
    { id: 'sc_start', name: 'SC START', cat: 'System', icon: 'play_circle', desc: 'Start a service', useCase: 'SC START MyService', fields: [{ label: 'Service Name', type: 'text', req: true }] },
    { id: 'sc_stop', name: 'SC STOP', cat: 'System', icon: 'stop_circle', desc: 'Stop a service', useCase: 'SC STOP MyService', fields: [{ label: 'Service Name', type: 'text', req: true }] },
    { id: 'sc_pause', name: 'SC PAUSE', cat: 'System', icon: 'pause_circle', desc: 'Pause a service', useCase: 'SC PAUSE MyService', fields: [{ label: 'Service Name', type: 'text', req: true }] },
    { id: 'sc_continue', name: 'SC CONTINUE', cat: 'System', icon: 'replay', desc: 'Continue a paused service', useCase: 'SC CONTINUE MyService', fields: [{ label: 'Service Name', type: 'text', req: true }] },
    { id: 'sc_interrogate', name: 'SC INTERROGATE', cat: 'System', icon: 'contact_support', desc: 'Interrogate a service', useCase: 'SC INTERROGATE MyService', fields: [{ label: 'Service Name', type: 'text', req: true }] },
    { id: 'sc_create', name: 'SC CREATE', cat: 'System', icon: 'add_box', desc: 'Create a new service', useCase: 'SC CREATE ...', fields: [{ label: 'Service Name', type: 'text', req: true }, { label: 'binPath', type: 'text', req: true }, { label: 'Options', type: 'text', placeholder: 'start= auto' }] },
    { id: 'sc_delete', name: 'SC DELETE', cat: 'System', icon: 'delete_forever', desc: 'Delete a service', useCase: 'SC DELETE MyService', fields: [{ label: 'Service Name', type: 'text', req: true }] },
    // --- ACLs ---
    { id: 'icacls', name: 'ICACLS (Advanced)', cat: 'System', icon: 'security', desc: 'Advanced Manage ACLs', useCase: 'ICACLS file.txt /grant User:F', fields: [{ label: 'File/Folder', type: 'text', req: true }, { label: 'Arguments', type: 'text', placeholder: '/grant User:F', req: true }] },
    { id: 'icacls_grant', name: 'ICACLS Grant', cat: 'System', icon: 'person_add', desc: 'Grant permissions', useCase: 'ICACLS "file.txt" /grant User:F', fields: [{ label: 'File/Folder', type: 'text', req: true }, { label: 'User', type: 'text', req: true }, { label: 'Permission', type: 'select', options: ['Full Control (F)', 'Modify (M)', 'Read/Execute (RX)', 'Read (R)', 'Write (W)'] }] },
    { id: 'icacls_deny', name: 'ICACLS Deny', cat: 'System', icon: 'person_remove', desc: 'Deny permissions', useCase: 'ICACLS "file.txt" /deny User:F', fields: [{ label: 'File/Folder', type: 'text', req: true }, { label: 'User', type: 'text', req: true }, { label: 'Permission', type: 'select', options: ['Full Control (F)', 'Modify (M)', 'Read/Execute (RX)', 'Read (R)', 'Write (W)'] }] },
    { id: 'icacls_remove', name: 'ICACLS Remove', cat: 'System', icon: 'person_off', desc: 'Remove user permissions', useCase: 'ICACLS "file.txt" /remove User', fields: [{ label: 'File/Folder', type: 'text', req: true }, { label: 'User', type: 'text', req: true }] },
    { id: 'icacls_reset', name: 'ICACLS Reset', cat: 'System', icon: 'settings_backup_restore', desc: 'Reset ACLs to default', useCase: 'ICACLS "C:\\*" /reset /T', fields: [{ label: 'File/Folder', type: 'text', req: true }] },
    { id: 'icacls_save', name: 'ICACLS Save', cat: 'System', icon: 'save', desc: 'Backup ACLs to a file', useCase: 'ICACLS "C:\\" /save acl_backup /T', fields: [{ label: 'Path', type: 'text', req: true }, { label: 'Backup File', type: 'text', req: true }] },
    { id: 'icacls_restore', name: 'ICACLS Restore', cat: 'System', icon: 'restore', desc: 'Restore ACLs from a file', useCase: 'ICACLS "C:\\" /restore acl_backup', fields: [{ label: 'Path', type: 'text', req: true }, { label: 'Backup File', type: 'text', req: true }] },
    // --- Task Scheduler ---
    { id: 'schtasks', name: 'SCHTASKS (Advanced)', cat: 'System', icon: 'schedule', desc: 'Advanced Task Scheduler', fields: [{ label: 'Params', type: 'text', placeholder: '/Query /FO LIST' }] },
    { id: 'schtasks_create', name: 'SCHTASKS Create', cat: 'System', icon: 'add_alarm', desc: 'Create a scheduled task', useCase: 'SCHTASKS /Create ...', fields: [{ label: 'Schedule', type: 'select', options: ['MINUTE', 'HOURLY', 'DAILY', 'WEEKLY', 'MONTHLY', 'ONCE'], req: true }, { label: 'Task Name', type: 'text', req: true }, { label: 'Task Run', type: 'text', req: true }] },
    { id: 'schtasks_run', name: 'SCHTASKS Run', cat: 'System', icon: 'play_arrow', desc: 'Run a scheduled task', useCase: 'SCHTASKS /Run /TN MyTask', fields: [{ label: 'Task Name', type: 'text', req: true }] },
    { id: 'schtasks_end', name: 'SCHTASKS End', cat: 'System', icon: 'stop', desc: 'Stop a running task', useCase: 'SCHTASKS /End /TN MyTask', fields: [{ label: 'Task Name', type: 'text', req: true }] },
    { id: 'schtasks_delete', name: 'SCHTASKS Delete', cat: 'System', icon: 'delete_sweep', desc: 'Delete a scheduled task', useCase: 'SCHTASKS /Delete /TN MyTask /F', fields: [{ label: 'Task Name', type: 'text', req: true }] },
    { id: 'schtasks_change', name: 'SCHTASKS Change', cat: 'System', icon: 'edit_calendar', desc: 'Change a scheduled task', useCase: 'SCHTASKS /Change /TN MyTask /DISABLE', fields: [{ label: 'Task Name', type: 'text', req: true }, { label: 'Arguments', type: 'text', req: true, placeholder: '/DISABLE' }] },
    { id: 'schtasks_query', name: 'SCHTASKS Query', cat: 'System', icon: 'event_note', desc: 'Query scheduled tasks', useCase: 'SCHTASKS /Query /FO LIST /V', fields: [] },

    // NETWORK
    { id: 'ipconfig', name: 'IPCONFIG', cat: 'Network', icon: 'wifi', desc: 'Network info', useCase: 'IPCONFIG /all', fields: [{ label: 'Action', type: 'select', options: ['Show All (/all)', 'Release (/release)', 'Renew (/renew)', 'Flush DNS (/flushdns)'] }] },
    { id: 'ping', name: 'PING', cat: 'Network', icon: 'network_check', desc: 'Test connection', fields: [{ label: 'Target', type: 'text', placeholder: '8.8.8.8', req: true }] },
    { id: 'net_user', name: 'NET USER', cat: 'Network', icon: 'person', desc: 'Manage users', useCase: 'NET USER username password /ADD', fields: [{ label: 'Username', type: 'text' }, { label: 'Command', type: 'text' }] },
    { id: 'net_use', name: 'NET USE', cat: 'Network', icon: 'link', desc: 'Map drive', useCase: 'NET USE Z: \\\\server\\share', fields: [{ label: 'Drive', type: 'text' }, { label: 'Path', type: 'text' }] },
    { id: 'net_view', name: 'NET VIEW', cat: 'Network', icon: 'lan', desc: 'List PCs in network', useCase: 'NET VIEW', fields: [] },
    { id: 'netstat', name: 'NETSTAT', cat: 'Network', icon: 'route', desc: 'Network connections', useCase: 'NETSTAT -an', fields: [{ label: 'Flags', type: 'text', placeholder: '-an' }] },
    { id: 'ftp', name: 'FTP', cat: 'Network', icon: 'upload_file', desc: 'File Transfer Protocol', useCase: 'FTP -s:script.txt host.com', fields: [{ label: 'Host', type: 'text' }, { label: 'Arguments', type: 'text', placeholder: '-s:script.txt' }] },
    { id: 'curl', name: 'cURL Download', cat: 'Network', icon: 'download', desc: 'Download a file from URL', useCase: 'curl -o file.zip http://example.com/file.zip', fields: [{ label: 'URL', type: 'text', req: true }, { label: 'Output File', type: 'text', req: true }, { label: 'Flags', type: 'text', placeholder: '-L' }] },

    // PYTHON
    { id: 'py_run', name: 'Python Run', cat: 'Python', icon: 'play_arrow', desc: 'Run script', fields: [{ label: 'Script', type: 'text', placeholder: 'main.py' }] },
    { id: 'py_venv', name: 'Create Venv', cat: 'Python', icon: 'folder_zip', desc: 'python -m venv', fields: [{ label: 'Env Name', type: 'text', placeholder: 'venv' }] },
    { id: 'pip_install', name: 'Pip Install', cat: 'Python', icon: 'download', desc: 'Install package', useCase: 'pip install requests', fields: [{ label: 'Package', type: 'text', req: true }] },
    { id: 'pip_freeze', name: 'Pip Freeze', cat: 'Python', icon: 'list', desc: 'List packages', useCase: 'pip freeze > requirements.txt', fields: [{ label: 'Output File', type: 'text', placeholder: 'requirements.txt' }] },
    { id: 'pip_upgrade', name: 'Pip Upgrade', cat: 'Python', icon: 'upgrade', desc: 'Upgrade pip', useCase: 'python -m pip install --upgrade pip', fields: [] },

    // JAVA
    { id: 'java_run', name: 'Java Run', cat: 'Java', icon: 'play_arrow', desc: 'Run Java class or JAR', useCase: 'java -jar app.jar', fields: [{ label: 'Target', type: 'text', placeholder: 'MyClass or -jar app.jar', req: true }, { label: 'Arguments', type: 'text' }] },
    { id: 'javac', name: 'Java Compile', cat: 'Java', icon: 'build', desc: 'Compile .java files', useCase: 'javac Main.java', fields: [{ label: 'Files', type: 'text', placeholder: '*.java', req: true }, { label: 'Flags', type: 'text', placeholder: '-d bin' }] },
    { id: 'jar_create', name: 'JAR Create', cat: 'Java', icon: 'archive', desc: 'Create JAR archive', useCase: 'jar cf app.jar *.class', fields: [{ label: 'JAR Name', type: 'text', placeholder: 'app.jar', req: true }, { label: 'Files', type: 'text', placeholder: '*.class', req: true }, { label: 'Flags', type: 'text', placeholder: 'cf' }] },
    { id: 'jar_extract', name: 'JAR Extract', cat: 'Java', icon: 'unarchive', desc: 'Extract JAR archive', useCase: 'jar xf app.jar', fields: [{ label: 'JAR File', type: 'text', req: true }, { label: 'Flags', type: 'text', placeholder: 'xf' }] },
    { id: 'javadoc', name: 'Javadoc', cat: 'Java', icon: 'description', desc: 'Generate documentation', useCase: 'javadoc -d doc src/*.java', fields: [{ label: 'Source Files', type: 'text', req: true }, { label: 'Output Dir', type: 'text', placeholder: '-d doc' }] },
    { id: 'java_version', name: 'Java Version', cat: 'Java', icon: 'info', desc: 'Check Java version', useCase: 'java -version', fields: [] },
    { id: 'jps', name: 'JPS', cat: 'Java', icon: 'list', desc: 'List Java processes', useCase: 'jps -l', fields: [{ label: 'Flags', type: 'text', placeholder: '-l' }] },
    { id: 'jshell', name: 'JShell', cat: 'Java', icon: 'terminal', desc: 'Interactive Java Shell', useCase: 'jshell', fields: [] },
    { id: 'keytool_gen', name: 'Keytool Gen', cat: 'Java', icon: 'vpn_key', desc: 'Generate Keystore', useCase: 'keytool -genkey ...', fields: [{ label: 'Keystore File', type: 'text', req: true }, { label: 'Alias', type: 'text', req: true }] },
    { id: 'keytool_list', name: 'Keytool List', cat: 'Java', icon: 'list_alt', desc: 'List Keystore entries', useCase: 'keytool -list ...', fields: [{ label: 'Keystore File', type: 'text', req: true }] },

    // GIT
    { id: 'git_init', name: 'Git Init', cat: 'Git', icon: 'start', desc: 'Initialize repo', fields: [] },
    { id: 'git_clone', name: 'Git Clone', cat: 'Git', icon: 'cloud_download', desc: 'Clone repo', fields: [{ label: 'Repo URL', type: 'text', req: true }] },
    { id: 'git_status', name: 'Git Status', cat: 'Git', icon: 'info', desc: 'Check status', fields: [] },
    { id: 'git_add', name: 'Git Add', cat: 'Git', icon: 'add_circle', desc: 'Stage changes', fields: [{ label: 'Files', type: 'text', placeholder: '.', req: true }] },
    { id: 'git_commit', name: 'Git Commit', cat: 'Git', icon: 'check_circle', desc: 'Commit changes', fields: [{ label: 'Message', type: 'text', req: true }] },
    { id: 'git_push', name: 'Git Push', cat: 'Git', icon: 'upload', desc: 'Push changes', fields: [] },
    { id: 'git_pull', name: 'Git Pull', cat: 'Git', icon: 'sync', desc: 'Pull changes', fields: [] },
    { id: 'git_checkout', name: 'Git Checkout', cat: 'Git', icon: 'switch_access_shortcut', desc: 'Switch branch', fields: [{ label: 'Branch', type: 'text', req: true }] },

    // ARCHIVE
    { id: '7zip_create', name: '7-Zip Create', cat: 'Archive', icon: 'archive', desc: 'Create 7-Zip archive (7z.exe needed in PATH)', useCase: '7z a archive.7z *.txt', fields: [{ label: 'Archive Name', type: 'text', req: true }, { label: 'Files to Add', type: 'text', req: true }, { label: 'Flags', type: 'text' }] },
    { id: '7zip_extract', name: '7-Zip Extract', cat: 'Archive', icon: 'unarchive', desc: 'Extract 7-Zip archive (7z.exe needed in PATH)', useCase: '7z x archive.7z -oOutput', fields: [{ label: 'Archive Name', type: 'text', req: true }, { label: 'Flags', type: 'text', placeholder: '-oOutput' }] },

    // EXTERNAL
    { id: 'custom_cmd', name: 'Custom Command', cat: 'External', icon: 'terminal', desc: 'Run any command', fields: [{ label: 'Command Line', type: 'text', req: true, placeholder: 'echo Hello' }] }
];

const presetLibrary = [
    {
        name: 'Smart System Maintenance', desc: 'Clean Temp, Reset Update Svc, SFC Scan', icon: 'build', blocks: [
            { id: 'echo_off', values: [] },
            { id: 'title', values: ['System Maintenance Tool'] },
            { id: 'color', values: ['0B (Aqua)'] },
            { id: 'echo', values: ['Checking for Admin privileges...'] },
            { id: 'custom_cmd', values: ['net session >nul 2>&1'] },
            { id: 'if_start', values: ['NEQ (!=)', '%errorLevel%', '0'] },
            { id: 'echo', values: ['ERROR: Please run as Administrator!'] },
            { id: 'pause', values: [] },
            { id: 'exit', values: [] },
            { id: 'block_end', values: [] },
            { id: 'echo', values: ['Stopping Windows Update Services...'] },
            { id: 'sc_stop', values: ['wuauserv'] },
            { id: 'sc_stop', values: ['bits'] },
            { id: 'echo', values: ['Cleaning Update Cache...'] },
            { id: 'rd', values: ['%windir%\\SoftwareDistribution', 'Yes (/Q/S)'] },
            { id: 'echo', values: ['Restarting Services...'] },
            { id: 'sc_start', values: ['wuauserv'] },
            { id: 'sc_start', values: ['bits'] },
            { id: 'echo', values: ['Running System File Checker...'] },
            { id: 'custom_cmd', values: ['sfc /scannow'] },
            { id: 'echo', values: ['Cleaning Temp Files...'] },
            { id: 'del', values: ['%temp%\\*.*', 'Yes (/F/Q)'] },
            { id: 'echo', values: ['Maintenance Complete!'] },
            { id: 'pause', values: [] }
        ]
    },
    {
        name: 'Web Project Scaffolder', desc: 'Node.js + Python + Git Setup', icon: 'code', blocks: [
            { id: 'echo_off', values: [] },
            { id: 'title', values: ['Project Scaffolder'] },
            { id: 'set_p', values: ['projName', 'Enter Project Name: '] },
            { id: 'md', values: ['%projName%'] },
            { id: 'cd', values: ['%projName%'] },
            { id: 'echo', values: ['Creating directories...'] },
            { id: 'md', values: ['src'] },
            { id: 'md', values: ['public'] },
            { id: 'md', values: ['tests'] },
            { id: 'echo', values: ['Initializing Git...'] },
            { id: 'git_init', values: [] },
            { id: 'echo_to_file', values: ['node_modules/', '.gitignore', 'Overwrite (>)'] },
            { id: 'echo_to_file', values: ['__pycache__/', '.gitignore', 'Append (>>)'] },
            { id: 'echo_to_file', values: ['*.log', '.gitignore', 'Append (>>)'] },
            { id: 'echo', values: ['Checking for Node.js...'] },
            { id: 'custom_cmd', values: ['node -v >nul 2>&1'] },
            { id: 'if_start', values: ['EQU (==)', '%errorLevel%', '0'] },
            { id: 'echo', values: ['Initializing NPM...'] },
            { id: 'custom_cmd', values: ['npm init -y'] },
            { id: 'else_start', values: [] },
            { id: 'echo', values: ['Node.js not found, skipping npm init.'] },
            { id: 'block_end', values: [] },
            { id: 'echo', values: ['Setup Python Venv?'] },
            { id: 'choice', values: ['Create Venv?', 'YN'] },
            { id: 'if_start', values: ['EQU (==)', '%errorLevel%', '1'] },
            { id: 'py_venv', values: ['venv'] },
            { id: 'block_end', values: [] },
            { id: 'echo', values: ['Project %projName% created successfully!'] },
            { id: 'pause', values: [] }
        ]
    },
    {
        name: 'Secure Backup Rotation', desc: 'Robocopy Mirror + 7-Zip Archive', icon: 'security', blocks: [
            { id: 'echo_off', values: [] },
            { id: 'title', values: ['Backup Utility'] },
            { id: 'set', values: ['source', 'C:\\Work'] },
            { id: 'set', values: ['dest', 'D:\\Backups'] },
            { id: 'set', values: ['timestamp', '%date:~-4,4%%date:~-10,2%%date:~-7,2%_%time:~0,2%%time:~3,2%'] },
            { id: 'set', values: ['timestamp', '%timestamp: =0%'] },
            { id: 'echo', values: ['Starting Backup for %timestamp%...'] },
            { id: 'md', values: ['%dest%\\%timestamp%'] },
            { id: 'echo', values: ['Mirroring files...'] },
            { id: 'robocopy', values: ['%source%', '%dest%\\%timestamp%', '/MIR /R:3 /W:5 /NFL /NDL'] },
            { id: 'echo', values: ['Robocopy finished with code %errorLevel%'] },
            { id: 'echo', values: ['Compressing backup...'] },
            { id: 'if_start', values: ['EXIST', 'C:\\Program Files\\7-Zip\\7z.exe', ''] },
            { id: 'custom_cmd', values: ['"C:\\Program Files\\7-Zip\\7z.exe" a -t7z -mx9 "%dest%\\backup_%timestamp%.7z" "%dest%\\%timestamp%"'] },
            { id: 'echo', values: ['Cleaning up uncompressed folder...'] },
            { id: 'rd', values: ['%dest%\\%timestamp%', 'Yes (/Q/S)'] },
            { id: 'else_start', values: [] },
            { id: 'echo', values: ['7-Zip not found, keeping uncompressed folder.'] },
            { id: 'block_end', values: [] },
            { id: 'echo', values: ['Backup Complete.'] },
            { id: 'pause', values: [] }
        ]
    },
    {
        name: 'Network Diagnostic Suite', desc: 'Ping, DNS, WiFi Export, Speed Test', icon: 'router', blocks: [
            { id: 'echo_off', values: [] },
            { id: 'title', values: ['NetDiag Suite'] },
            { id: 'echo', values: ['--- Connectivity Test ---'] },
            { id: 'ping', values: ['8.8.8.8'] },
            { id: 'if_start', values: ['NEQ (!=)', '%errorLevel%', '0'] },
            { id: 'echo', values: ['Internet Connection Failed! Attempting repair...'] },
            { id: 'ipconfig', values: ['Release (/release)'] },
            { id: 'ipconfig', values: ['Renew (/renew)'] },
            { id: 'ipconfig', values: ['Flush DNS (/flushdns)'] },
            { id: 'block_end', values: [] },
            { id: 'echo', values: ['--- WiFi Profiles ---'] },
            { id: 'custom_cmd', values: ['netsh wlan show profiles'] },
            { id: 'echo', values: ['Exporting WiFi profiles to folder...'] },
            { id: 'md', values: ['wifi_backup'] },
            { id: 'custom_cmd', values: ['netsh wlan export profile key=clear folder=wifi_backup'] },
            { id: 'echo', values: ['--- Active Connections ---'] },
            { id: 'netstat', values: ['-an'] },
            { id: 'echo', values: ['Diagnostics Complete.'] },
            { id: 'pause', values: [] }
        ]
    },
    {
        name: 'Bulk File Organizer', desc: 'Sorts files by extension into folders', icon: 'folder_open', blocks: [
            { id: 'echo_off', values: [] },
            { id: 'title', values: ['File Organizer'] },
            { id: 'set_p', values: ['targetDir', 'Enter full path to organize (e.g. C:\\Downloads): '] },
            { id: 'pushd', values: ['%targetDir%'] },
            { id: 'echo', values: ['Organizing Images...'] },
            { id: 'md', values: ['Images'] },
            { id: 'move', values: ['*.jpg', 'Images'] },
            { id: 'move', values: ['*.png', 'Images'] },
            { id: 'move', values: ['*.gif', 'Images'] },
            { id: 'echo', values: ['Organizing Documents...'] },
            { id: 'md', values: ['Documents'] },
            { id: 'move', values: ['*.pdf', 'Documents'] },
            { id: 'move', values: ['*.docx', 'Documents'] },
            { id: 'move', values: ['*.txt', 'Documents'] },
            { id: 'echo', values: ['Organizing Archives...'] },
            { id: 'md', values: ['Archives'] },
            { id: 'move', values: ['*.zip', 'Archives'] },
            { id: 'move', values: ['*.rar', 'Archives'] },
            { id: 'move', values: ['*.7z', 'Archives'] },
            { id: 'echo', values: ['Organizing Executables...'] },
            { id: 'md', values: ['Installers'] },
            { id: 'move', values: ['*.exe', 'Installers'] },
            { id: 'move', values: ['*.msi', 'Installers'] },
            { id: 'popd', values: [] },
            { id: 'echo', values: ['Organization Complete!'] },
            { id: 'pause', values: [] }
        ]
    },
    {
        name: 'Git Repo Auto-Sync', desc: 'Pull, Add, Commit, Push with timestamp', icon: 'sync', blocks: [
            { id: 'echo_off', values: [] },
            { id: 'title', values: ['Git Auto-Sync'] },
            { id: 'echo', values: ['Checking Git Status...'] },
            { id: 'git_status', values: [] },
            { id: 'echo', values: ['Pulling latest changes...'] },
            { id: 'git_pull', values: [] },
            { id: 'if_start', values: ['NEQ (!=)', '%errorLevel%', '0'] },
            { id: 'echo', values: ['Pull failed! Resolve conflicts manually.'] },
            { id: 'pause', values: [] },
            { id: 'exit', values: [] },
            { id: 'block_end', values: [] },
            { id: 'echo', values: ['Staging changes...'] },
            { id: 'git_add', values: ['.'] },
            { id: 'set', values: ['timestamp', '%date% %time%'] },
            { id: 'echo', values: ['Committing with timestamp: %timestamp%'] },
            { id: 'git_commit', values: ['Auto-sync: %timestamp%'] },
            { id: 'echo', values: ['Pushing...'] },
            { id: 'git_push', values: [] },
            { id: 'echo', values: ['Sync Complete!'] },
            { id: 'timeout', values: ['5'] }
        ]
    }
];