const PowerShellEngine = {
    id: 'PowerShell',
    name: 'PowerShell',
    icon: 'code',
    fileExtension: '.ps1',

    // Placeholder data
    commands: [
        { id: 'write_host', name: 'Write-Host', cat: 'Basic', icon: 'terminal', desc: 'Write to console', fields: [{ label: 'Message', type: 'text' }] },
        { id: 'get_process', name: 'Get-Process', cat: 'System', icon: 'memory', desc: 'Get running processes', fields: [] }
    ],
    presets: [],

    generateCode: function (returnLines = false) {
        const lines = [{ text: "# PowerShell Script Generated by WinScript Builder", blockIndex: null }];
        if (returnLines) return lines;
        return lines.map(l => l.text).join('\n');
    },

    highlightSyntax: function (text) {
        return text; // No highlighting yet
    },

    parse: function (text) { return []; }
};